language: node_js
node_js:
  - 13

branches:
  only:
    - master

cache: npm

before_script:
  - "npm run-script clean"
script:
  - "npm run-script build"

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: safecornerscoffee-blog
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: public
  wait-until-deployed: true

notifications:
  email:
    recipients:
      - safecorners.mobile@gmail.com